---
all:
  hosts:
    raspi:
      ansible_host: 192.168.0.48
      ansible_user: pi
    # Will promp for password when executed with -k flag
    windows:
      ansible_host: 192.168.2.101
      ansible_user: lukas
      ansible_connection: winrm
      ansible_winrm_server_cert_validation: ignore 
